# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from arm_move/mission.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class mission(genpy.Message):
  _md5sum = "1ebf46cc34619c6ab6b248306e7f7e41"
  _type = "arm_move/mission"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 type
geometry_msgs/Point T
geometry_msgs/Point E
geometry_msgs/Point L
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['type','T','E','L']
  _slot_types = ['int32','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,T,E,L

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mission, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = 0
      if self.T is None:
        self.T = geometry_msgs.msg.Point()
      if self.E is None:
        self.E = geometry_msgs.msg.Point()
      if self.L is None:
        self.L = geometry_msgs.msg.Point()
    else:
      self.type = 0
      self.T = geometry_msgs.msg.Point()
      self.E = geometry_msgs.msg.Point()
      self.L = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i9d().pack(_x.type, _x.T.x, _x.T.y, _x.T.z, _x.E.x, _x.E.y, _x.E.z, _x.L.x, _x.L.y, _x.L.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.T is None:
        self.T = geometry_msgs.msg.Point()
      if self.E is None:
        self.E = geometry_msgs.msg.Point()
      if self.L is None:
        self.L = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.type, _x.T.x, _x.T.y, _x.T.z, _x.E.x, _x.E.y, _x.E.z, _x.L.x, _x.L.y, _x.L.z,) = _get_struct_i9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i9d().pack(_x.type, _x.T.x, _x.T.y, _x.T.z, _x.E.x, _x.E.y, _x.E.z, _x.L.x, _x.L.y, _x.L.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.T is None:
        self.T = geometry_msgs.msg.Point()
      if self.E is None:
        self.E = geometry_msgs.msg.Point()
      if self.L is None:
        self.L = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 76
      (_x.type, _x.T.x, _x.T.y, _x.T.z, _x.E.x, _x.E.y, _x.E.z, _x.L.x, _x.L.y, _x.L.z,) = _get_struct_i9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i9d = None
def _get_struct_i9d():
    global _struct_i9d
    if _struct_i9d is None:
        _struct_i9d = struct.Struct("<i9d")
    return _struct_i9d
